# Generated by Django 4.2.30 on 2026-06-13 10:12

import apps.shared.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
        ('dossiers', '0007_remove_registrecivil_nom_complet_personne_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etat_civil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(default='Sénégalaise', max_length=50, verbose_name='Nationalité')),
                ('telephone', models.CharField(max_length=20, validators=[apps.shared.validators.validate_phone_senegal], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
                ('numero_cni', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.shared.validators.validate_cni], verbose_name='Numéro CNI')),
                ('numero_passeport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de passeport')),
                ('date_expiration_cni', models.DateField(blank=True, null=True, verbose_name="Date d'expiration CNI")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='attributiondossier',
            options={'verbose_name': 'Attribution de Dossier', 'verbose_name_plural': 'Attributions de Dossiers'},
        ),
        migrations.AlterModelOptions(
            name='journalattribution',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Journal Attribution', 'verbose_name_plural': 'Journaux Attributions'},
        ),
        migrations.AlterModelOptions(
            name='profilagent',
            options={'verbose_name': 'Profil Agent', 'verbose_name_plural': 'Profils Agents'},
        ),
        migrations.RemoveConstraint(
            model_name='attributiondossier',
            name='etat_civil_unique_active_attribution_per_dossier',
        ),
        migrations.RemoveConstraint(
            model_name='profilagent',
            name='etat_civil_profilagent_valid_score',
        ),
        migrations.RemoveConstraint(
            model_name='profilagent',
            name='etat_civil_profilagent_valid_capacity',
        ),
        migrations.RemoveIndex(
            model_name='attributiondossier',
            name='etat_civil__statut_a32aaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='attributiondossier',
            name='etat_civil__agent_i_2014f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='attributiondossier',
            name='etat_civil__date_li_71cb37_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalattribution',
            name='etat_civil__dossier_eab844_idx',
        ),
        migrations.RemoveIndex(
            model_name='profilagent',
            name='etat_civil__statut__8e0212_idx',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='date_limite_sla',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='date_traitement_effectif',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='score_matching_initial',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='attributiondossier',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='action',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='agent_concerne',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='anciennes_valeurs',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='motif_detaille',
        ),
        migrations.RemoveField(
            model_name='journalattribution',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profilagent',
            name='capacite_maximale',
        ),
        migrations.RemoveField(
            model_name='profilagent',
            name='competences_types_dossiers',
        ),
        migrations.RemoveField(
            model_name='profilagent',
            name='dossiers_traites_historique',
        ),
        migrations.RemoveField(
            model_name='profilagent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profilagent',
            name='score_performance_global',
        ),
        migrations.RemoveField(
            model_name='profilagent',
            name='statut_actuel',
        ),
        migrations.RemoveField(
            model_name='profilagent',
            name='temps_moyen_traitement_minutes',
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='agent_actuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributions_actuelles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='ancien_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_attributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='date_attribution',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='date_limite_traitement',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='est_reattribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='justification_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='notification_24h_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='notification_48h_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='responsable_attribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='score_attribution',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='source_attribution',
            field=models.CharField(choices=[('auto', 'Automatique'), ('ia', 'Intelligence Artificielle'), ('manuel', 'Manuel'), ('reattribution', 'Réattribution'), ('superviseur', 'Superviseur')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='agent_apres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='agent_avant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='dossier_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='libelle_action',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='score_calcule',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilagent',
            name='charge_maximale',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profilagent',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilagent',
            name='score_global',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilagent',
            name='specialites',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profilagent',
            name='taux_respect_delais',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilagent',
            name='taux_reussite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilagent',
            name='temps_moyen_traitement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attributiondossier',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='dossiers.dossier'),
        ),
        migrations.AlterField(
            model_name='attributiondossier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attributiondossier',
            name='niveau_priorite',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('eleve', 'Élevé'), ('normal', 'Normal'), ('faible', 'Faible')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalattribution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profilagent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilagent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profilagent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='attributiondossier',
            table='attribution_dossier',
        ),
        migrations.AlterModelTable(
            name='journalattribution',
            table='attribution_journal',
        ),
        migrations.AlterModelTable(
            name='profilagent',
            table='attribution_profil_agent',
        ),
        migrations.AddField(
            model_name='citoyen',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_guichet', to='communes.commune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddIndex(
            model_name='citoyen',
            index=models.Index(fields=['numero_cni'], name='etat_civil__numero__a32778_idx'),
        ),
        migrations.AddIndex(
            model_name='citoyen',
            index=models.Index(fields=['telephone'], name='etat_civil__telepho_264d32_idx'),
        ),
        migrations.AddIndex(
            model_name='citoyen',
            index=models.Index(fields=['nom', 'prenom'], name='etat_civil__nom_0c65ed_idx'),
        ),
    ]
