# Generated by Django 4.2.30 on 2026-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_citizenprofile_cni_document_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_capabilities',
            field=models.JSONField(blank=True, default=list, help_text="Liste des étapes pour lesquelles cet agent est habilité (ex: ['reception', 'verification'])", verbose_name="Capacités de l'agent"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('agent', 'Agent'), ('civil_admin', 'Administrateur de mairie'), ('civil_admin_supervisor', 'Administrateur général de mairie'), ('super_admin', 'Super administrateur')], db_index=True, default='citizen', max_length=25, verbose_name='Rôle'),
        ),
    ]
