# Generated by Django 4.2.30 on 2026-06-14 15:53

from django.db import migrations

def migrate_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    for user in User.objects.filter(role__in=['reception_agent', 'verification_agent', 'approval_agent']):
        capabilities = list(user.agent_capabilities) if user.agent_capabilities else []
        if user.role == 'reception_agent' and 'reception' not in capabilities:
            capabilities.append('reception')
        elif user.role == 'verification_agent' and 'verification' not in capabilities:
            capabilities.append('verification')
        elif user.role == 'approval_agent' and 'approval' not in capabilities:
            capabilities.append('approval')
            
        user.role = 'agent'
        user.agent_capabilities = capabilities
        user.save()

def reverse_migrate_roles(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_agent_capabilities_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
