# Generated by Django 4.2.30 on 2026-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='chemin_cachet_communal',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du cachet communal'),
        ),
        migrations.AddField(
            model_name='commune',
            name='chemin_cachet_nominal',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du cachet nominal'),
        ),
        migrations.AddField(
            model_name='commune',
            name='chemin_signature_officier',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Chemin de la signature de l'officier"),
        ),
        migrations.AddField(
            model_name='commune',
            name='devise',
            field=models.CharField(default='Un Peuple - Un But - Une Foi', max_length=255, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='commune',
            name='nom_commune_officiel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom officiel de la commune'),
        ),
        migrations.AddField(
            model_name='commune',
            name='nom_officier_etat_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'officier d'état civil"),
        ),
        migrations.AddField(
            model_name='commune',
            name='numero_registre_courant',
            field=models.IntegerField(default=1, verbose_name='Numéro de registre courant'),
        ),
        migrations.AddField(
            model_name='commune',
            name='prefixe_deces',
            field=models.CharField(default='DEC-2026-', max_length=20, verbose_name='Préfixe Décès'),
        ),
        migrations.AddField(
            model_name='commune',
            name='prefixe_mariage',
            field=models.CharField(default='MAR-2026-', max_length=20, verbose_name='Préfixe Mariage'),
        ),
        migrations.AddField(
            model_name='commune',
            name='prefixe_residence',
            field=models.CharField(default='RES-2026-', max_length=20, verbose_name='Préfixe Résidence'),
        ),
    ]
