# Generated by Django 4.2.30 on 2026-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_remove_dossier_is_for_third_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='citoyen_guichet',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='heure_naissance',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='jugement_suppletif',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='nom_enfant',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='numero_jugement',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='prenom_mere',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='prenom_pere',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='prenoms_enfant',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='sexe',
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='nom_complet_personne',
            field=models.CharField(default='', max_length=255, verbose_name='Nom complet sur le registre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrecivil',
            name='date_naissance_personne',
            field=models.DateField(default='2026-01-01', verbose_name='Date de naissance sur le registre'),
            preserve_default=False,
        ),
    ]
