# Generated by Django 4.2.30 on 2026-06-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0012_dossier_citoyen_guichet_alter_dossier_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrecivil',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du père'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='profession_mere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession de la mère'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='profession_pere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession du père'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
    ]
