# Generated by Django 4.2.30 on 2026-06-13 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0012_dossier_citoyen_guichet_alter_dossier_citizen'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='dossiers.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de reçu'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence externe'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Validé'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
